# Generated by Django 4.2 on 2023-05-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('RecipeCategory', models.CharField(max_length=255)),
                ('RecipeInstructions', models.TextField()),
                ('CookTime', models.IntegerField()),
                ('PrepTime', models.IntegerField()),
                ('TotalTime', models.IntegerField()),
                ('RecipeIngredientParts', models.TextField()),
                ('Calories', models.FloatField()),
                ('FatContent', models.FloatField()),
                ('SaturatedFatContent', models.FloatField()),
                ('CholesterolContent', models.FloatField()),
                ('SodiumContent', models.FloatField()),
                ('CarbohydrateContent', models.FloatField()),
                ('FiberContent', models.FloatField()),
                ('SugarContent', models.FloatField()),
                ('ProteinContent', models.FloatField()),
            ],
        ),
    ]
